console.log({ "process.env.NEXT_PUBLIC_NFT_STORAGE_API_KEY": process.env.NEXT_PUBLIC_NFT_STORAGE_API_KEY })
export const configs = {
    NODE_ENV: process.env.NODE_ENV,
    COINGECKO_BASE_URL: process.env.COINGECKO_BASE_URL,
    INFURA_API_KEY: process.env.INFURA_API_KEY,
    GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    NFT_STORAGE_API_KEY: process.env.NFT_STORAGE_API_KEY,
    DEPLOYER_PRIVATE_KEY: process.env.DEPLOYER_PRIVATE_KEY,
    ETHEREUM_EXPLORER_API_KEY: process.env.ETHEREUM_EXPLORER_API_KEY,
    ARBITRUM_EXPLORER_API_KEY: process.env.ARBITRUM_EXPLORER_API_KEY,
    OPTIMISM_EXPLORER_API_KEY: process.env.OPTIMISM_EXPLORER_API_KEY,
    POLYGON_EXPLORER_API_KEY: process.env.POLYGON_EXPLORER_API_KEY,
    NEXT_PUBLIC_DEPLOYER_PRIVATE_KEY: process.env.NEXT_PUBLIC_DEPLOYER_PRIVATE_KEY,
    NEXT_PUBLIC_ALCHEMY_KEY: process.env.NEXT_PUBLIC_ALCHEMY_KEY,
    NEXT_PUBLIC_INFURA_API_KEY: process.env.NEXT_PUBLIC_INFURA_API_KEY,
    NEXT_PUBLIC_NFT_STORAGE_API_KEY: process.env.NEXT_PUBLIC_NFT_STORAGE_API_KEY
}; 